practice/docker/django/accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', RedirectView.as_view(url='/accounts/home/')),
    path('register/', views.register, name='register'),
]

practice/docker/django/config/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('', RedirectView.as_view(url='/accounts/home/')),
    path('auth/', include('social_django.urls', namespace='social')),
]

practice/docker/django/shop/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'shop'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('register/', views.register, name='register'),
]

practice/docker/django/shop/models.py
from django.db import models


class Book(models.Model):
    """本モデル"""

    class Meta(object):
        db_table = 'book'

    title = models.CharField(verbose_name='タイトル', max_length=255)
    price = models.PositiveIntegerField(verbose_name='価格', null=True, blank=True)

    def __str__(self):
        return self.title

practice/docker/django/shop/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ObjectDoesNotExist

from .models import Book


class RegisterForm(forms.ModelForm):
    """ユーザー登録画面用のフォーム"""

    class Meta:
        # 利用するモデルクラスを指定
        model = Book
        # 利用するモデルのフィールドを指定
        fields = ('title', 'price',)
        # ウィジェットを上書き
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'タイトル'}),
            'price': forms.TextInput(attrs={'placeholder': '価格'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # フィールドの属性を書き換え
        self.fields['title'].required = True
        self.fields['price'].required = True

    def clean_title(self):
        value = self.cleaned_data['title']
        """
            バリデーション
        """
        return value

    def clean_price(self):
        value = self.cleaned_data['price']
        """
            バリデーション
        """
        return value

    def clean(self):
        """
            バリデーション
        """
        super().clean()

practice/docker/django/shop/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .models import Book
from .forms import RegisterForm

logger = logging.getLogger(__name__)


class RegisterView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'form': RegisterForm(),
        }
        return render(request, 'shop/register.html', context)

    def post(self, request, *args, **kwargs):
        logger.info("You're in post!!!")
        # リクエストからフォームを作成
        form = RegisterForm(request.POST)

        # バリデーション
        if not form.is_valid():
            # バリデーションNGの場合はアカウント登録画面のテンプレートを再表示
            return render(request, 'shop/register.html', {'form': form})

        form.save()

        # フラッシュメッセージを画面に表示
        messages.info(request, "登録しました。")

        # list画面にリダイレクト
        return redirect(reverse('shop:list'))


register = RegisterView.as_view()


class ListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        queryset = Book.objects.all()
        context = {
            'book_list': queryset,
        }
        print(queryset)
        return render(request, 'shop/list.html', context)

    def post(self, request, *args, **kwargs):
        logger.info("You're in post!!!")

        if 'delete' in request.POST:
            book_id = request.POST['delete']
            book_item = Book.objects.get(id=book_id)
            book_item.delete()

            # フラッシュメッセージを画面に表示
            messages.info(request, "削除しました。")

        elif 'update' in request.POST:
            book_id = request.POST['update']
            book_title = request.POST[f'title_{book_id}']
            book_price = request.POST[f'price_{book_id}']

            book_item = Book.objects.get(id=book_id)
            book_item.title = book_title
            book_item.price = book_price
            book_item.save()

            # フラッシュメッセージを画面に表示
            messages.info(request, "更新しました。")

        # list画面にリダイレクト
        return redirect(reverse('shop:list'))


list = ListView.as_view()

practice/docker/django/templates/shop/list.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}home{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
<div class="content">list</div>

{% csrf_token %}

{% if user.is_authenticated %}
    <p class="display-4">Hello, {{ user.username }}</p>
    <a class="lead" href="{% url 'shop:register' %}">register</a>
    <h1>list</h1>
    <form action="" method="post" class="ui form">
        {% for book in book_list %}
            <div>
                <input type="text" name="title_{{ book.id }}" value="{{ book.title }}">
                <input type="text" name="price_{{ book.id }}" value="{{ book.price }}">円
                <button type="submit" name="update" value="{{ book.id }}">商品更新</button>
                <button type="submit" name="delete" value="{{ book.id }}">商品削除</button>
            </div>
        {% endfor %}
        {% csrf_token %}
    </form>
{% else %}
    <a class="lead" href="{% url 'accounts:login' %}">Log in</a>
{% endif %}

{% endblock %}

practice/docker/django/templates/shop/register.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}home{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
<div class="content">register</div>

{% if user.is_authenticated %}
    <p class="display-4">Hello, {{ user.username }}</p>
    <a class="lead" href="{% url 'shop:list' %}">list</a>
    <h1>register</h1>
    <form action="" method="post" class="ui form">
        {# --- 全体エラーメッセージ --- #}
        {% if form.non_field_errors %}
            <div class="ui red message">
                <div class="header">エラー</div>
                <ul class="list">
                    {% for non_field_error in form.non_field_errors %}
                    <li>{{ non_field_error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            {% for field in form %}
            <div class="field{% if field.errors %} error{% endif %}">
                {# --- 入力フィールド --- #}
                <div class="ui input{% if field.errors %} error{% endif %}">
                    {{ field }}
                </div>
                {# --- 入力フィールドごとのエラーメッセージ（最初のエラーのみを表示） --- #}
                {% if field.errors %}
                <p class="red message">{{ field.errors.0 }}</p>
                {% endif %}
            </div>
            {% endfor %}

            {% csrf_token %}
            <button type="submit" class="ui fluid teal submit button">商品登録</button>
    </form>
{% else %}
    <a class="lead" href="{% url 'accounts:login' %}">Log in</a>
{% endif %}

{% endblock %}