practice/python/django/uploader/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('uploader/', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

practice/python/django/uploader/web/urls.py
from django.urls import path
from . import views


app_name = 'web'
urlpatterns = [
    path('local/', views.file_upload, name='file_upload'),
    path('s3/root', views.RootDocumentCreateView.as_view(), name='s3_root'),
    path('s3/schema', views.SchemaDocumentCreateView.as_view(), name='s3_schema'),
    path('download/<int:pk>/<str:doc>', views.download, name='download'),
]

practice/python/django/uploader/web/models.py
from django.db import models
from django.utils import timezone
from config.storage_backends import SchemaStorage


class FilePath(models.Model):
    file_id = models.CharField(unique=True, max_length=200)
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(default=timezone.now)


class RootDocument(models.Model):
    file_name = models.CharField(max_length=50)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    upload = models.FileField()


class SchemaDocument(models.Model):
    file_name = models.CharField(max_length=50)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    upload = models.FileField(storage=SchemaStorage())

practice/python/django/uploader/web/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()

practice/python/django/uploader/web/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from .forms import UploadFileForm
from .models import FilePath
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import RootDocument
from .models import SchemaDocument
import uuid
import datetime
from django.shortcuts import get_object_or_404
from django.http import FileResponse


def download(request, pk, doc):
    if doc == 'root':
        doc_model = RootDocument
    elif doc == 'schema':
        doc_model = SchemaDocument

    upload_file = get_object_or_404(doc_model, pk=pk)
    download_file = upload_file.upload
    return FileResponse(download_file)


def paginate_query(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


def file_upload(request):
    if request.method == 'POST':
        try:
            form = UploadFileForm(request.POST, request.FILES)
            if not form.is_valid():
                raise Exception('Validation Error')
            file_obj = request.FILES['file']
            handle_uploaded_file(file_obj)
            messages.success(request, "アップロードが成功しました。")
        except Exception as e:
            messages.error(request, "アップロードが失敗しました。")
            print(e)
        
        return HttpResponseRedirect('/web')

    else:
        form = UploadFileForm()
        queryset = FilePath.objects.order_by("-id")
        page_obj = paginate_query(request, queryset, settings.PAGE_PER_ITEM)
        context = {
            'form': form,
            'page_obj': page_obj,
            'path': request.path
        }
    return render(request, 'file_upload.html', context)


def handle_uploaded_file(file_obj):
    title = file_obj.name

    if '.' in title:
        file_id = '.'.join(title.split('.')[:-1]) + '_' + str(uuid.uuid4()) + '.' + title.split('.')[-1]
    else:
        file_id = title + '_' + str(uuid.uuid4())

    fp = FilePath(file_id=file_id, title=title)
    path = 'media/' + file_id
    with open(path, 'wb+') as destination:
        for chunk in file_obj.chunks():
            destination.write(chunk)
    
    fp.save()


class S3UploadCreateView(CreateView):
    def post(self, request, *args, **kwargs):
        file_obj = request.FILES.get('upload')
        if file_obj is not None:
            file_name_org = file_obj.name
            file_name = file_obj.name
            dt_now = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
            if '.' in file_name:
                file_name = '.'.join(file_name.split('.')[:-1]) + '_' + dt_now + '.' + file_name.split('.')[-1]
            else:
                file_name += '_' + dt_now

            file_obj.name = file_name
            request.FILES['upload'] = file_obj

        # super().post(request, *args, **kwargs) を参考に override
        self.object = None
        form = self.get_form()
        if not form.is_valid():
            messages.error(request, "アップロードが失敗しました。データが不正です。")
            return self.form_invalid(form)
        try:
            self.object = form.save(commit=False)
            self.object.file_name = file_name_org
            self.object.save()
            messages.success(request, "アップロードが成功しました。")
        except Exception as e:
            print(e)
            messages.error(request, "アップロードが失敗しました。S3へアクセスできません。")
            return self.form_invalid(form)

        return self.form_valid(form)


class RootDocumentCreateView(S3UploadCreateView):
    model = RootDocument
    fields = ['upload',]
    success_url = reverse_lazy('s3_root') # urls.py の name を指定する
    template_name = "web/document.html" 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        documents = RootDocument.objects.order_by("-id")
        page_obj = paginate_query(self.request, documents, settings.PAGE_PER_ITEM)
        context['page_obj'] = page_obj
        context['path'] = self.request.path
        context['doc'] = 'root'

        return context


class SchemaDocumentCreateView(S3UploadCreateView):
    model = SchemaDocument
    fields = ['upload',]
    success_url = reverse_lazy('s3_schema') # urls.py の name を指定する
    template_name = "web/document.html" 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        documents = SchemaDocument.objects.order_by("-id")
        page_obj = paginate_query(self.request, documents, settings.PAGE_PER_ITEM)
        context['page_obj'] = page_obj
        context['path'] = self.request.path
        context['doc'] = 'schema'

        return context

practice/python/django/uploader/templates/_message.html
{% block messages %}
{% if messages %}
    <br>
    {% for message in messages %}
    <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ message }}</div>
    {% endfor %}
{% endif %}
{% endblock messages %}

practice/python/django/uploader/templates/base.html
<!doctype html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %}{% endblock %}</title>

    {# --- css --- #}
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/dropify.min.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-collapse justify-content-center">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="navbar-brand" href="#">S3 Uploader</a>
        </li>
        </ul>
    </div>
    </nav>
<main>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
        {% block content %}{% endblock %}
        </div>
        <div class="col-md-3"></div>
    </div>
    {% block extra_js %}{% endblock %}
    {# --- js --- #}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/dropify.min.js' %}"></script>
    <script>
        $(function(){
          $('.dropify').dropify();
        })
    </script>
</main>
</body>
</html>

practice/python/django/uploader/templates/file_upload.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}ファイルアップロード{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
    <br>
    <h2 style="text-align: center;">ファイルアップロード</h2>
    <div style="text-align: center;">
      s3://test-mida-storage{{ path }}
    </div>
    <form action="" method="POST" class="ui form" enctype="multipart/form-data">
      {% csrf_token %}  
      <div class="form-group">
        <label for="inputText">File</label>
        <input type="file" class="dropify" name="file" required id="id_file" />
      </div>
      <br>
      <div style="text-align: center">
        <button type="submit" class="btn btn-primary">アップロード</button>
      </div>
    </form>

    {% include '_message.html' %}

    {% if page_obj|length > 0 %}
      <br><br>
      <h2 style="text-align: center;">アップロードファイルリスト</h2>
      <table class="table">
        <thead>
          <tr>
            <td>No</td>
            <td>ファイル名</td>
            <td>アップロード日時</td>
          </tr>
        </thead>
        {% for file_path in page_obj %}
        <tbody>
          <tr>
            <td>{{ file_path.id }}</td>
            <td><a href="/media/{{ file_path.file_id }}" download="{{ file_path.title }}" target="_blank">{{ file_path.title }}</a></td>
            <td>{{ file_path.created_at|date:"Y-m-j H:i" }}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>

      {% include 'pagination.html' %}
    {% endif %}

{% endblock %}

practice/python/django/uploader/templates/pagination.html
<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li><a class="page-link text-primary d-inline-block" href="?page={{ page_obj.previous_page_number }}">前</a></li>
            {% else %}
                <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">前</div></li>
            {% endif %}

            {% for link_page in page_obj.paginator.page_range %}
                {% if link_page %}
                    {% if link_page == page_obj.number %}
                        <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">{{ link_page }}</div></li>
                    {% else %}
                        <li><a class="page-link text-primary d-inline-block" href="?page={{ link_page }}">{{ link_page }}</a></li>
                    {% endif %}
                {% else %}
                    <li class="disabled"><a class="page-link text-secondary d-inline-block text-muted" href="#">・・・</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a class="page-link text-primary d-inline-block" href="?page={{ page_obj.next_page_number }}">次</a></li>
            {% else %}
                <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">次</div></li>
            {% endif %}
        </ul>
    </nav>
</div>

practice/python/django/uploader/templates/web/document.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}ファイルアップロード{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
  <br>
  <h2 style="text-align: center;">ファイルアップロード</h2>
  <div style="text-align: center;">
    s3://test-mida-storage{{ path }}
  </div>
  <form action="" method="POST" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}  
    <div class="form-group">
      <label for="inputText">File</label>
      <input type="file" class="dropify" name="upload" required id="id_upload" />
    </div>
    <br>
    <div style="text-align: center">
      <button type="submit" class="btn btn-primary">アップロード</button>
    </div>
  </form>

  {% include '_message.html' %}

  {% if page_obj %}
      <br><br>
      <h2 style="text-align: center;">アップロードファイルリスト</h2>
      <table class="table">
        <thead>
          <tr>
            <td>No</td>
            <td>ファイル名</td>
            <td>アップロード日時</td>
            <td>ファイルサイズ</td>
          </tr>
        </thead>
        {% for document in page_obj %}
        <tbody>
          <tr>
            <td>{{ document.id }}</td>
            <!-- <td><a href="{{ document.upload.url }}" download="{{ document.file_name }}" target="_blank">{{ document.file_name }}</a></td> -->
            <td><a href="{% url 'web:download' document.id doc %}" download="{{ document.file_name }}" target="_blank">{{ document.file_name }}</a></td>
            <td>{{ document.uploaded_at|date:"Y-m-j H:i" }}</td>
            <td>{{ document.upload.size|filesizeformat }}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>

      {% include 'pagination.html' %}
    {% endif %}

{% endblock %}